import { PhotoModel } from '../models/photo.model';

export const MOCK_PHOTOS_DATA: PhotoModel[] = [
  {
    id: '10',
    title: 'Test',
    url: 'https://picsum.photos/id/',
    views: 1234,
    likes: 99,
    unlikes: 11,
    idLastPhoto: undefined,
    idNextPhoto: 20,
  },
  {
    id: '20',
    title: 'Test',
    url: 'https://picsum.photos/id/',
    views: 1234,
    likes: 99,
    unlikes: 11,
    idLastPhoto: 10,
    idNextPhoto: 30,
  },
  {
    id: '30',
    title: 'Test',
    url: 'https://picsum.photos/id/',
    views: 1234,
    likes: 99,
    unlikes: 11,
    idLastPhoto: 20,
    idNextPhoto: 40,
  },
  {
    id: '40',
    title: 'Test',
    url: 'https://picsum.photos/id/',
    views: 1234,
    likes: 99,
    unlikes: 11,
    idLastPhoto: 30,
    idNextPhoto: 50,
  },
  {
    id: '50',
    title: 'Test',
    url: 'https://picsum.photos/id/',
    views: 1234,
    likes: 99,
    unlikes: 11,
    idLastPhoto: 40,
    idNextPhoto: 60,
  },
  {
    id: '60',
    title: 'Test',
    url: 'https://picsum.photos/id/',
    views: 1234,
    likes: 99,
    unlikes: 11,
    idLastPhoto: 50,
    idNextPhoto: 70,
  },
  {
    id: '70',
    title: 'Test',
    url: 'https://picsum.photos/id/',
    views: 1234,
    likes: 99,
    unlikes: 11,
    idLastPhoto: 60,
    idNextPhoto: 80,
  },
  {
    id: '80',
    title: 'Test',
    url: 'https://picsum.photos/id/',
    views: 1234,
    likes: 99,
    unlikes: 11,
    idLastPhoto: 70,
    idNextPhoto: 90,
  },
  {
    id: '90',
    title: 'Test',
    url: 'https://picsum.photos/id/',
    views: 1234,
    likes: 99,
    unlikes: 11,
    idLastPhoto: 80,
    idNextPhoto: 100,
  },
  {
    id: '100',
    title: 'Test',
    url: 'https://picsum.photos/id/',
    views: 1234,
    likes: 99,
    unlikes: 11,
    idLastPhoto: 90,
    idNextPhoto: 110,
  },
  {
    id: '110',
    title: 'Test',
    url: 'https://picsum.photos/id/',
    views: 1234,
    likes: 99,
    unlikes: 11,
    idLastPhoto: 100,
    idNextPhoto: 120,
  },
  {
    id: '120',
    title: 'Test',
    url: 'https://picsum.photos/id/',
    views: 1234,
    likes: 99,
    unlikes: 11,
    idLastPhoto: 110,
    idNextPhoto: 130,
  },
  {
    id: '130',
    title: 'Test',
    url: 'https://picsum.photos/id/',
    views: 1234,
    likes: 99,
    unlikes: 11,
    idLastPhoto: 120,
    idNextPhoto: 140,
  },
  {
    id: '140',
    title: 'Test',
    url: 'https://picsum.photos/id/',
    views: 1234,
    likes: 99,
    unlikes: 11,
    idLastPhoto: 130,
    idNextPhoto: 150,
  },
  {
    id: '150',
    title: 'Test',
    url: 'https://picsum.photos/id/',
    views: 1234,
    likes: 99,
    unlikes: 11,
    idLastPhoto: 140,
    idNextPhoto: 160,
  },
  {
    id: '160',
    title: 'Test',
    url: 'https://picsum.photos/id/',
    views: 1234,
    likes: 99,
    unlikes: 11,
    idLastPhoto: 150,
    idNextPhoto: 170,
  },
  {
    id: '170',
    title: 'Test',
    url: 'https://picsum.photos/id/',
    views: 1234,
    likes: 99,
    unlikes: 11,
    idLastPhoto: 160,
    idNextPhoto: 180,
  },
  {
    id: '180',
    title: 'Test',
    url: 'https://picsum.photos/id/',
    views: 1234,
    likes: 99,
    unlikes: 11,
    idLastPhoto: 170,
    idNextPhoto: 190,
  },
  {
    id: '190',
    title: 'Test',
    url: 'https://picsum.photos/id/',
    views: 1234,
    likes: 99,
    unlikes: 11,
    idLastPhoto: 180,
    idNextPhoto: 200,
  },
  {
    id: '200',
    title: 'Test',
    url: 'https://picsum.photos/id/',
    views: 1234,
    likes: 99,
    unlikes: 11,
    idLastPhoto: 180,
    idNextPhoto: 210,
  },
  {
    id: '210',
    title: 'Test',
    url: 'https://picsum.photos/id/',
    views: 1234,
    likes: 99,
    unlikes: 11,
    idLastPhoto: 200,
    idNextPhoto: 220,
  },
  {
    id: '220',
    title: 'Test',
    url: 'https://picsum.photos/id/',
    views: 1234,
    likes: 99,
    unlikes: 11,
    idLastPhoto: 210,
    idNextPhoto: 230,
  },
  {
    id: '230',
    title: 'Test',
    url: 'https://picsum.photos/id/',
    views: 1234,
    likes: 99,
    unlikes: 11,
    idLastPhoto: 220,
    idNextPhoto: 240,
  },
  {
    id: '240',
    title: 'Test',
    url: 'https://picsum.photos/id/',
    views: 1234,
    likes: 99,
    unlikes: 11,
    idLastPhoto: 230,
    idNextPhoto: 250,
  },
  {
    id: '250',
    title: 'Test',
    url: 'https://picsum.photos/id/',
    views: 1234,
    likes: 99,
    unlikes: 11,
    idLastPhoto: 240,
    idNextPhoto: 260,
  },
  {
    id: '260',
    title: 'Test',
    url: 'https://picsum.photos/id/',
    views: 1234,
    likes: 99,
    unlikes: 11,
    idLastPhoto: 250,
    idNextPhoto: 270,
  },
  {
    id: '270',
    title: 'Test',
    url: 'https://picsum.photos/id/',
    views: 1234,
    likes: 99,
    unlikes: 11,
    idLastPhoto: 260,
    idNextPhoto: 280,
  },
  {
    id: '280',
    title: 'Test',
    url: 'https://picsum.photos/id/',
    views: 1234,
    likes: 99,
    unlikes: 11,
    idLastPhoto: 270,
    idNextPhoto: 290,
  },
  {
    id: '290',
    title: 'Test',
    url: 'https://picsum.photos/id/',
    views: 1234,
    likes: 99,
    unlikes: 11,
    idLastPhoto: 280,
    idNextPhoto: 300,
  },
  {
    id: '300',
    title: 'Test',
    url: 'https://picsum.photos/id/',
    views: 1234,
    likes: 99,
    unlikes: 11,
    idLastPhoto: 290,
    idNextPhoto: 310,
  },
  {
    id: '310',
    title: 'Test',
    url: 'https://picsum.photos/id/',
    views: 1234,
    likes: 99,
    unlikes: 11,
    idLastPhoto: 300,
    idNextPhoto: 320,
  },
  {
    id: '320',
    title: 'Test',
    url: 'https://picsum.photos/id/',
    views: 1234,
    likes: 99,
    unlikes: 11,
    idLastPhoto: 310,
    idNextPhoto: 330,
  },
  {
    id: '330',
    title: 'Test',
    url: 'https://picsum.photos/id/',
    views: 1234,
    likes: 99,
    unlikes: 11,
    idLastPhoto: 320,
    idNextPhoto: 340,
  },
  {
    id: '340',
    title: 'Test',
    url: 'https://picsum.photos/id/',
    views: 1234,
    likes: 99,
    unlikes: 11,
    idLastPhoto: 330,
    idNextPhoto: 350,
  },
  {
    id: '350',
    title: 'Test',
    url: 'https://picsum.photos/id/',
    views: 1234,
    likes: 99,
    unlikes: 11,
    idLastPhoto: 340,
    idNextPhoto: 360,
  },
  {
    id: '360',
    title: 'Test',
    url: 'https://picsum.photos/id/',
    views: 1234,
    likes: 99,
    unlikes: 11,
    idLastPhoto: 350,
    idNextPhoto: 370,
  },
  {
    id: '370',
    title: 'Test',
    url: 'https://picsum.photos/id/',
    views: 1234,
    likes: 99,
    unlikes: 11,
    idLastPhoto: 360,
    idNextPhoto: 380,
  },
  {
    id: '380',
    title: 'Test',
    url: 'https://picsum.photos/id/',
    views: 1234,
    likes: 99,
    unlikes: 11,
    idLastPhoto: 370,
    idNextPhoto: 390,
  },
  {
    id: '390',
    title: 'Test',
    url: 'https://picsum.photos/id/',
    views: 1234,
    likes: 99,
    unlikes: 11,
    idLastPhoto: 380,
    idNextPhoto: 400,
  },
  {
    id: '400',
    title: 'Test',
    url: 'https://picsum.photos/id/',
    views: 1234,
    likes: 99,
    unlikes: 11,
    idLastPhoto: 390,
    idNextPhoto: 410,
  },
  {
    id: '410',
    title: 'Test',
    url: 'https://picsum.photos/id/',
    views: 1234,
    likes: 99,
    unlikes: 11,
    idLastPhoto: 400,
    idNextPhoto: 420,
  },
  {
    id: '420',
    title: 'Test',
    url: 'https://picsum.photos/id/',
    views: 1234,
    likes: 99,
    unlikes: 11,
    idLastPhoto: 410,
    idNextPhoto: 430,
  },
  {
    id: '430',
    title: 'Test',
    url: 'https://picsum.photos/id/',
    views: 1234,
    likes: 99,
    unlikes: 11,
    idLastPhoto: 420,
    idNextPhoto: 440,
  },
  {
    id: '440',
    title: 'Test',
    url: 'https://picsum.photos/id/',
    views: 1234,
    likes: 99,
    unlikes: 11,
    idLastPhoto: 430,
    idNextPhoto: 450,
  },
  {
    id: '450',
    title: 'Test',
    url: 'https://picsum.photos/id/',
    views: 1234,
    likes: 99,
    unlikes: 11,
    idLastPhoto: 440,
    idNextPhoto: 460,
  },
  {
    id: '460',
    title: 'Test',
    url: 'https://picsum.photos/id/',
    views: 1234,
    likes: 99,
    unlikes: 11,
    idLastPhoto: 450,
    idNextPhoto: 470,
  },
  {
    id: '470',
    title: 'Test',
    url: 'https://picsum.photos/id/',
    views: 1234,
    likes: 99,
    unlikes: 11,
    idLastPhoto: 460,
    idNextPhoto: 480,
  },
  {
    id: '480',
    title: 'Test',
    url: 'https://picsum.photos/id/',
    views: 1234,
    likes: 99,
    unlikes: 11,
    idLastPhoto: 470,
    idNextPhoto: 490,
  },
  {
    id: '490',
    title: 'Test',
    url: 'https://picsum.photos/id/',
    views: 1234,
    likes: 99,
    unlikes: 11,
    idLastPhoto: 480,
    idNextPhoto: 500,
  },
  {
    id: '500',
    title: 'Test',
    url: 'https://picsum.photos/id/',
    views: 1234,
    likes: 99,
    unlikes: 11,
    idLastPhoto: 490,
    idNextPhoto: undefined,
  },
];
